#!/bin/bash

sxhkd &

feh --bg-fill ~/Pictures/wallpaper.jpg

bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating


dunst &

xsetroot -cursor_name left_ptr

~/.config/picom/launch.sh
~/.config/polybar/launch.sh

bspc config focus_follows_pointer on

bspc config pointer_motion_interval   7
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner
